// src/utils/icons.ts
import * as LucideIcons from 'lucide-react';

// نگاشت نام آیکون‌ها به کامپوننت‌ها
export const iconMap: { [key: string]: React.ComponentType<any> } = {
  BookOpen: LucideIcons.BookOpen,
  Lightbulb: LucideIcons.Lightbulb,
  History: LucideIcons.History,
  Brain: LucideIcons.Brain,
  Baby: LucideIcons.Baby,
  Heart: LucideIcons.Heart,
  Book: LucideIcons.Book,
  Library: LucideIcons.Library,
  Pen: LucideIcons.Pen,
  Scroll: LucideIcons.Scroll,
  Globe: LucideIcons.Globe,
  Star: LucideIcons.Star,
  Award: LucideIcons.Award,
  Feather: LucideIcons.Feather,
  Headphones: LucideIcons.Headphones,
  Music: LucideIcons.Music,
  Film: LucideIcons.Film,
  Drama: LucideIcons.Drama,
  Rocket: LucideIcons.Rocket,
  FlaskConical: LucideIcons.FlaskConical,
  Microscope: LucideIcons.Microscope,
  Palette: LucideIcons.Palette,
  Paintbrush: LucideIcons.Paintbrush,
  Camera: LucideIcons.Camera,
  Map: LucideIcons.Map,
  Compass: LucideIcons.Compass,
  Clock: LucideIcons.Clock,
  Calendar: LucideIcons.Calendar,
  Sun: LucideIcons.Sun,
  Moon: LucideIcons.Moon,
  Cloud: LucideIcons.Cloud,
  Tree: LucideIcons.Trees,
  Flower: LucideIcons.Flower,
  Mountain: LucideIcons.Mountain,
  Droplet: LucideIcons.Droplet,
  Flame: LucideIcons.Flame,
  Shield: LucideIcons.Shield,
  Sword: LucideIcons.Sword,
  Castle: LucideIcons.Castle,
  Key: LucideIcons.Key,
  Lock: LucideIcons.Lock,
  Unlock: LucideIcons.Unlock,
  Eye: LucideIcons.Eye,
  EyeOff: LucideIcons.EyeOff,
  Sparkles: LucideIcons.Sparkles,
  Wand: LucideIcons.Wand,
  Gem: LucideIcons.Gem,
  Diamond: LucideIcons.Diamond,
  Trophy: LucideIcons.Trophy,
  Medal: LucideIcons.Medal,
  Gift: LucideIcons.Gift,
  Cake: LucideIcons.Cake,
  PartyPopper: LucideIcons.PartyPopper,
  
};


export const iconNamesMap: { [key: string]: string } = {
  BookOpen: 'کتاب باز',
  Lightbulb: 'لامپ',
  History: 'تاریخ',
  Brain: 'مغز',
  Baby: 'کودک',
  Heart: 'قلب',
  Book: 'کتاب',
  Library: 'کتابخانه',
  Pen: 'قلم',
  Scroll: 'طومار',
  Globe: 'جهان',
  Star: 'ستاره',
  Award: 'جایزه',
  Feather: 'پر',
  Headphones: 'هدفون',
  Music: 'موسیقی',
  Film: 'فیلم',
  Drama: 'تئاتر',
  Rocket: 'موشک',
  FlaskConical: 'لوله آزمایش',
  Microscope: 'میکروسکوپ',
  Palette: 'پالت رنگ',
  Paintbrush: 'قلم‌مو',
  Camera: 'دوربین',
  Map: 'نقشه',
  Compass: 'قطب‌نما',
  Clock: 'ساعت',
  Calendar: 'تقویم',
  Sun: 'خورشید',
  Moon: 'ماه',
  Cloud: 'ابر',
  Tree: 'درخت',
  Flower: 'گل',
  Mountain: 'کوه',
  Droplet: 'قطره',
  Flame: 'شعله',
  Shield: 'سپر',
  Sword: 'شمشیر',
  Castle: 'قلعه',
  Key: 'کلید',
  Lock: 'قفل',
  Unlock: 'باز کردن قفل',
  Eye: 'چشم',
  EyeOff: 'چشم بسته',
  Sparkles: 'جرقه',
  Wand: 'چوب جادویی',
  Gem: 'جواهر',
  Diamond: 'الماس',
  Trophy: 'جام',
  Medal: 'مدال',
  Gift: 'هدیه',
  Cake: 'کیک',
  PartyPopper: 'ترقه جشن',
};


export const iconList = Object.keys(iconMap).map((name) => ({
  name,
  displayName: iconNamesMap[name] || name, 
  Icon: iconMap[name],
}));

export const defaultIcon = { name: 'BookOpen', Icon: LucideIcons.BookOpen };